
export default function UKCounties() {

   return(
      [
         {
            "id":0,
            "value":"Avon"
         },
         {
            "id":1,
            "value":"Bedfordshire"
         },
         {
            "id":2,
            "value":"Berkshire"
         },
         {
            "id":3,
            "value":"Buckinghamshire"
         },
         {
            "id":4,
            "value":"Cambridgeshire"
         },
         {
            "id":5,
            "value":"Cheshire"
         },
         {
            "id":6,
            "value":"Cleveland"
         },
         {
            "id":7,
            "value":"Cornwall"
         },
         {
            "id":8,
            "value":"Cumbria"
         },
         {
            "id":9,
            "value":"Derbyshire"
         },
         {
            "id":10,
            "value":"Devon"
         },
         {
            "id":11,
            "value":"Dorset"
         },
         {
            "id":12,
            "value":"Durham"
         },
         {
            "id":13,
            "value":"East Sussex"
         },
         {
            "id":14,
            "value":"Essex"
         },
         {
            "id":15,
            "value":"Gloucestershire"
         },
         {
            "id":16,
            "value":"Hampshire"
         },
         {
            "id":17,
            "value":"Herefordshire"
         },
         {
            "id":18,
            "value":"Hertfordshire"
         },
         {
            "id":19,
            "value":"Isle of Wight"
         },
         {
            "id":20,
            "value":"Kent"
         },
         {
            "id":21,
            "value":"Lancashire"
         },
         {
            "id":22,
            "value":"Leicestershire"
         },
         {
            "id":23,
            "value":"Lincolnshire"
         },
         {
            "id":24,
            "value":"London"
         },
         {
            "id":25,
            "value":"Merseyside"
         },
         {
            "id":26,
            "value":"Middlesex"
         },
         {
            "id":27,
            "value":"Norfolk"
         },
         {
            "id":28,
            "value":"Northamptonshire"
         },
         {
            "id":29,
            "value":"Northumberland"
         },
         {
            "id":30,
            "value":"North Humberside"
         },
         {
            "id":31,
            "value":"North Yorkshire"
         },
         {
            "id":32,
            "value":"Nottinghamshire"
         },
         {
            "id":33,
            "value":"Oxfordshire"
         },
         {
            "id":34,
            "value":"Rutland"
         },
         {
            "id":35,
            "value":"Shropshire"
         },
         {
            "id":36,
            "value":"Somerset"
         },
         {
            "id":37,
            "value":"South Humberside"
         },
         {
            "id":38,
            "value":"South Yorkshire"
         },
         {
            "id":39,
            "value":"Staffordshire"
         },
         {
            "id":40,
            "value":"Suffolk"
         },
         {
            "id":41,
            "value":"Surrey"
         },
         {
            "id":42,
            "value":"Tyne and Wear"
         },
         {
            "id":43,
            "value":"Warwickshire"
         },
         {
            "id":44,
            "value":"West Midlands"
         },
         {
            "id":45,
            "value":"West Sussex"
         },
         {
            "id":46,
            "value":"West Yorkshire"
         },
         {
            "id":47,
            "value":"Wiltshire"
         },
         {
            "id":48,
            "value":"Worcestershire"
         },
         {
            "id":49,
            "value":"Clwyd"
         },
         {
            "id":50,
            "value":"Dyfed"
         },
         {
            "id":51,
            "value":"Gwent"
         },
         {
            "id":52,
            "value":"Gwynedd"
         },
         {
            "id":53,
            "value":"Mid Glamorgan"
         },
         {
            "id":54,
            "value":"Powys"
         },
         {
            "id":55,
            "value":"South Glamorgan"
         },
         {
            "id":56,
            "value":"West Glamorgan"
         },
         {
            "id":57,
            "value":"Aberdeenshire"
         },
         {
            "id":58,
            "value":"Angus"
         },
         {
            "id":59,
            "value":"Argyll"
         },
         {
            "id":60,
            "value":"Ayrshire"
         },
         {
            "id":61,
            "value":"Banffshire"
         },
         {
            "id":62,
            "value":"Berwickshire"
         },
         {
            "id":63,
            "value":"Bute"
         },
         {
            "id":64,
            "value":"Caithness"
         },
         {
            "id":65,
            "value":"Clackmannanshire"
         },
         {
            "id":66,
            "value":"Dumfriesshire"
         },
         {
            "id":67,
            "value":"Dunbartonshire"
         },
         {
            "id":68,
            "value":"East Lothian"
         },
         {
            "id":69,
            "value":"Fife"
         },
         {
            "id":70,
            "value":"Inverness-shire"
         },
         {
            "id":71,
            "value":"Kincardineshire"
         },
         {
            "id":72,
            "value":"Kinross-shire"
         },
         {
            "id":73,
            "value":"Kirkcudbrightshire"
         },
         {
            "id":74,
            "value":"Lanarkshire"
         },
         {
            "id":75,
            "value":"Midlothian"
         },
         {
            "id":76,
            "value":"Moray"
         },
         {
            "id":77,
            "value":"Nairnshire"
         },
         {
            "id":78,
            "value":"Orkney"
         },
         {
            "id":79,
            "value":"Peeblesshire"
         },
         {
            "id":80,
            "value":"Perthshire"
         },
         {
            "id":81,
            "value":"Renfrewshire"
         },
         {
            "id":82,
            "value":"Ross-shire"
         },
         {
            "id":83,
            "value":"Roxburghshire"
         },
         {
            "id":84,
            "value":"Selkirkshire"
         },
         {
            "id":85,
            "value":"Shetland"
         },
         {
            "id":86,
            "value":"Stirlingshire"
         },
         {
            "id":87,
            "value":"Sutherland"
         },
         {
            "id":88,
            "value":"West Lothian"
         },
         {
            "id":89,
            "value":"Wigtownshire"
         },
         {
            "id":90,
            "value":"Antrim"
         },
         {
            "id":91,
            "value":"Armagh"
         },
         {
            "id":92,
            "value":"Down"
         },
         {
            "id":93,
            "value":"Fermanagh"
         },
         {
            "id":94,
            "value":"Londonderry"
         },
         {
            "id":95,
            "value":"Tyrone"
         }
      ]
   )
}